name: Build palen1x

on:
  push:
    branches: [ surface ]
    paths:
      - scripts/**
      - build.sh
      - inittab
      - version
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build for amd64
        run: |
          sudo ARCH=amd64 ./build.sh && sudo mv -v work/*.iso .

      - name: Build for i686
        run: |
          sudo ARCH=i686 ./build.sh && sudo mv -v work/*.iso .

      - name: Publish release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          TAG="${GITHUB_REF##*/}-${GITHUB_SHA:0:7}"
          gh release create "$TAG" --draft --title "Draft Release"
          gh release upload "$TAG" ./*.iso
